name: Python application test with pytest

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        cd src/seasons
        pytest

    - name: Run pytest with coverage
      run: |
        cd $GITHUB_WORKSPACE
        pytest --cov=.
